### ISSUE TITLE
Re-evaluate module license

### ISSUE THREAD

**Issue by mnaser** [duritong/puppet-sysctl#38]
Hi @duritong 

First, thanks for pushing up such a useful module.  It's consumed heavily and the reach of it's usage is extremely cool.  However, Puppet has switched all of it's modules to use the Apache 2.0 license during the 2.7 release, you can read the article which explains some of the benefits and reasons behind the change:

https://puppet.com/blog/relicensing-puppet-to-apache-2-0

I see that the library is licensed under GPL at the moment.  Would it be possible to look into relicensing it under Apache 2.0 as that will help make things easier in terms of consuming the modules?

If you have any questions, please let me know.  If you also lack the time and resources, I can push up a pull request with the license updates to make it easier for you.  If you want to maintain the same license model, then it is your decision and I also have no problem with that, feel free to close the issue in that case.

Thank you!
Mohammed

**Comment by mnaser** [comment]
Hi there,

Just a small friendly ping if there has been any updates on this.

Thanks :)
Mohammed

**Comment by duritong** [comment]
I am not really interested in changing it. Mainly, because I think the GPL is a much better License than Apache 2.0 and honestly I don't understand why it should be changed. What makes it easier to consume?

E.g. various commercial OpenStack distributions are shipping this module, as it's part of the set of the modules consumed by the upstream Puppet OpenStack project. And there wasn't a single one asking for a change. So why should it be changed now?

**Comment by ttx** [comment]
I suspect the various OpenStack distributions shipping this module missed the potential license issue there, and rely on the upstream Puppet-OpenStack project to avoid those. You should not have Apache licensed software depending on GPL modules, as it may be considered derivative work. LGPL, MIT, BSD would all be fine.

**Comment by ttx** [comment]
@duritong 
To clarify (OpenStack Foundation staff here), OpenStack will have to stop using this module if you don't relicense it. We'll have to migrate OpenStack Puppet modules to another (Apache-2 licensed) sysctl module... 

We'd rather not have to do that since your module works for us and migrating is always painful. But we'll respect your decision as module author, you decide on licensing :)

Please let us know what your final decision is on this.

**Comment by duritong** [comment]
Hi @ttx thanks for pointing me to that. I'd like to understand why this is needed, so I can make my own opinion about it.

They way I know OpenStack I am pretty sure one can read up somewhere about the reasoning, behind why the project is enforcing all licenses to Apache-2. Have some pointers? Thanks!

**Comment by ttx** [comment]
Thanks for looking into this!

You can find OpenStack licensing rules at:
https://governance.openstack.org/tc/reference/licensing.html

Basically our Puppet-OpenStack modules are released under Apache-2 license (as is all "OpenStack" software, as mandated by the bylaws of the OpenStack Foundation) and Apache-2 software cannot depend on GPL-licensed dependencies. Apache-2, LGPL, MIT, BSD (both forms), PSF, ISC, and MPL are all fine.

**Comment by duritong** [comment]
So besides that none of the links explains why GPLed libraries can't be used (it just says they are incompatible): From what I know is that re-licensing requires approval from each past-contributor. Who will collect these approvals? What will be done if one of the contributors can't be reached or does not agree on the change? Afaik code must be rewritten. This is how I remember the re-licensing of puppet itself.

I am maintaining this module in my spare time and I am not interested to do that tedious work, just because some lawyers of a US-based entity want to be on the safe side.
I am not saying this module can't be relicensed, just that I am not interested in spending my spare time on the bureaucratic efforts for a move where still nobody was able to explain the reasoning behind it.

**Comment by ttx** [comment]
The reasoning for why GPLed libraries can't be used in Apache-licensed software really resides in the terms of the GPL license, although you can find references elsewhere (like in https://en.wikipedia.org/wiki/License_compatibility). That said, you're right, it ultimately is down to lawyers wanted to be on the safe side.

I totally understand that if the module has a lot of code authors, it's too much work for you to relicense it. Thanks for considering it !
